Repository bookcrush/httpPerfectGuide, pull requests merged in 2019-10, with the labels that each got.

#50 [bookCrush/httpPerfectGuide] chap4_ 김준형
  chapter_4/README.md
Labels: 챕터4

#48 [bookCrush/httpPerfectGuide] chap4_고현주
  chapter_4/README.md
Labels: 챕터4

#53 [bookCrush/httpPerfectGuide] chap4_김나영
  chapter_4/README.md
Labels: 챕터4

#47 [bookCrush/httpPerfectGuide] chap4_한재우
  chapter_4/README.md
Labels: 챕터4

#52 [bookCrush/httpPerfectGuide] chap4_류지환
  chapter_4/README.md
Labels: 챕터4

#56 [bookCrush/httpPerfectGuide] chap5_한재우
  chapter_5/README.md
Labels: 챕터5

#55 [bookCrush/httpPerfectGuide] chap5_김준형
  chapter_5/README.md
Labels: 챕터5

#54 [bookCrush/httpPerfectGuide] chap5_고석진
  chapter_5/chap5_고석진.md
Labels: 챕터5

#57 [bookCrush/httpPerfectGuide] chap5_김나영
  chapter_5/README.md
Labels: 챕터5

#58 [bookCrush/httpPerfectGuide] chap5_고현주
  chapter_5/README.md
Labels: 챕터5

#35 [bookCrush/httpPerfectGuide] chap3_홍유정
  chapter_3/README.md
Labels: 챕터3

#41 [bookCrush/httpPerfectGuide] chap3_이보라
  chapter_3/README.md
  chapter_3/chap3_이보라.md
Labels: 챕터3
