Repository bookcrush/httpPerfectGuide, pull requests merged in 2020-02, with the labels that each got.

#119 [bookCrush/httpPerfectGuide] chapter_16 고석진
  chapter_16/고석진.md
Labels: 챕터16

#126 Merge pull request #126 from bookcrush/chapter_17_고석진
  chapter_17/고석진.md
Labels: 챕터17

#116 [bookCrush/httpPerfectGuide] chapter_15 고석진
  chapter_15/고석진.md
Labels: 챕터15

#113 [bookCrush/httpPerfectGuide] chapter_15 김나영
  chapter_15/README.md
Labels: 챕터15

#115 [bookCrush/httpPerfectGuide] chapter_15 한재우
  chapter_15/README.md
Labels: 챕터15

#114 [bookCrush/httpPerfectGuide] chapter_15 고현주
  chapter_15/README.md
Labels: 챕터15

#112 [bookCrush/httpPerfectGuide] chapter_15 이승규
  chapter_15/README.md
Labels: 챕터15

#129 [bookCrush/httpPerfectGuide] chapter18_이승규
  chapter_18/README.md
Labels: 챕터18

#130 [bookCrush/httpPerfectGuide] chapter18_김나영
  chapter_18/README.md
Labels: 챕터18

#131 [bookCrush/httpPerfectGuide] chapter18_한재우
  chapter_18/README.md
Labels: 챕터18
