Repository bookcrush/httpPerfectGuide, pull requests merged in 2020-01, with the labels that each got.

#109 [bookCrush/httpPerfectGuide] chap13_김나영
  chapter_13/README.md
Labels: 챕터13

#111 [bookCrush/httpPerfectGuide] chapter_14 김나영
  chapter_14/README.md
Labels: 챕터14

#103 [bookCrush/httpPerfectGuide] chapter_13 고석진.md 추가
  chapter_13/고석진.md
Labels: 챕터13

#106 [bookCrush/httpPerfectGuide] chap13_이승규
  chapter_13/README.md
Labels: 챕터13

#108 [bookCrush/httpPerfectGuide] chap13_한재우
  chapter_13/README.md
Labels: 챕터13

#110 [bookCrush/httpPerfectGuide] chap14_이승규
  chapter_14/README.md
Labels: 챕터14

#107 [bookCrush/httpPerfectGuide] chapter_14 고석진.md 추가
  chapter_14/chapter_14_고석진.md
Labels: 챕터14

#128 [bookCrush/httpPerfectGuide] chapter17_홍유정
  chapter_17/README.md
Labels: 챕터17

#125 [bookCrush/httpPerfectGuide] chapter_17 이승규
  chapter_17/README.md
Labels: 챕터17

#124 [bookCrush/httpPerfectGuide] chapter17_한재우
  chapter_17/README.md
Labels: 챕터17

#127 [bookCrush/httpPerfectGuide] chapter_17 김나영
  chapter_17/README.md
Labels: 챕터17

#118 Merge pull request #118 from bookcrush/chap16_홍유정
  chapter_16/README.md
Labels: 챕터16

#120 Merge pull request #120 from bookcrush/chap16_이승규
  chapter_16/README.md
Labels: 챕터16

#121 Merge pull request #121 from bookcrush/chap16_한재우
  chapter_16/README.md
Labels: 챕터16

#122 Merge pull request #122 from bookcrush/chap16_고현주
  chapter_16/README.md
Labels: 챕터16

#117 [bookCrush/httpPerfectGuide] chapter_15 홍유정
  chapter_15/README.md
Labels: 챕터15

#123 [bookCrush/httpPerfectGuide] chapter_16 김나영
  chapter_16/README.md
Labels: 챕터16
